apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "dbaas.redhat.com/v1beta1",
          "kind": "ProviderConnection",
          "metadata": {
            "name": "providerconnection-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "dbaas.redhat.com/v1beta1",
          "kind": "ProviderInstance",
          "metadata": {
            "name": "providerinstance-sample"
          },
          "spec": {
            "inventoryRef": {
              "name": "test",
              "namespace": "openshift-dbaas-operator"
            },
            "provisioningParameters": {
              "cloudProvider": "AWS",
              "name": "dbaas",
              "plan": "SERVERLESS",
              "regions": "us-east-2",
              "spendLimit": "0"
            }
          }
        },
        {
          "apiVersion": "dbaas.redhat.com/v1beta1",
          "kind": "ProviderInventory",
          "metadata": {
            "name": "providerinventory-sample"
          },
          "spec": {
            "spec": {
              "credentialsRef": {
                "name": "dbaas-vendor-credentials"
              }
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.24.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: provider-operator-example.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ProviderConnection is the Schema for the providerconnections API
      displayName: Provider Connection
      kind: ProviderConnection
      name: providerconnections.dbaas.redhat.com
      version: v1beta1
    - description: ProviderInstance is the Schema for the providerinstances API
      displayName: Provider Instance
      kind: ProviderInstance
      name: providerinstances.dbaas.redhat.com
      version: v1beta1
    - description: ProviderInventory is the Schema for the providerinventories API
      displayName: Provider Inventory
      kind: ProviderInventory
      name: providerinventories.dbaas.redhat.com
      version: v1beta1
  description: The GitHub repository provides a operator example for integrating database
    providers with the OpenShift Database Access/DBaaS Operator. The examples are
    intended to help developers understand how to create their operator and use the
    operator to with DBaaS operator.
  displayName: DBaaS Provider Operator Example
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - dbaasproviders
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - dbaasproviders/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - providerconnections
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - providerconnections/finalizers
          verbs:
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - providerconnections/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - providerinstances
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - providerinstances/finalizers
          verbs:
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - providerinstances/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - providerinventories
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - providerinventories/finalizers
          verbs:
          - update
        - apiGroups:
          - dbaas.redhat.com
          resources:
          - providerinventories/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: provider-operator-example-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: provider-operator-example-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: INSTALL_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: SYNC_PERIOD_MIN
                  value: "180"
                image: quay.io/ecosystem-appeng/provider-operator-example:v0.0.1
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: provider-operator-example-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: provider-operator-example-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - dbaas
  - database
  - operator
  links:
  - name: Provider Operator Example
    url: https://provider-operator-example.domain
  maturity: alpha
  provider:
    name: DBaaS Operator
    url: https://github.com/RHEcosystemAppEng/dbaas-operator
  version: 0.0.1
