apiVersion: dbaas.redhat.com/v1beta1
kind: ProviderInstance
metadata:
  name: providerinstance-sample
spec:
  inventoryRef:
    name: test
    namespace: openshift-dbaas-operator
  provisioningParameters:
    cloudProvider: AWS
    name: dbaas
    plan: SERVERLESS
    regions: us-east-2
    spendLimit: '0'
